In [1]:
from sklearn import datasets
from sklearn import svm
from sklearn.model_selection import train_test_split
import numpy as np

In [2]:
# 데이터셋을 읽고 훈련 집합과 테스트 집합으로 분할
digit=datasets.load_digits()
x_train,x_test,y_train,y_test=train_test_split(digit.data,digit.target,train_size=0.8)

In [3]:
# svm의 분류 모델 SVC를 학습
s=svm.SVC(gamma=0.001, max_iter=2020113345)
s.fit(x_train,y_train)

res=s.predict(x_test)

In [4]:
# 혼동 행렬 구함
conf=np.zeros((10,10))
for i in range(len(res)):
    conf[res[i]][y_test[i]]+=1
print(conf)

[[40.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 41.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 31.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 46.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. 41.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0. 34.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1. 28.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 31.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. 28.  1.]
 [ 0.  0.  0.  0.  0.  1.  0.  1.  0. 35.]]


In [5]:
# 정확률 측정하고 출력
no_correct=0
for i in range(10):
    no_correct+=conf[i][i]
accuracy=no_correct/len(res)
print("테스트 집합에 대한 정확률은", accuracy*100, "%입니다.")

테스트 집합에 대한 정확률은 98.61111111111111 %입니다.
